"use strict";(self.webpackChunkqodly=self.webpackChunkqodly||[]).push([["44405"],{60133:function(e,n,r){r.r(n),r.d(n,{metadata:()=>o,contentTitle:()=>a,default:()=>h,assets:()=>l,toc:()=>c,frontMatter:()=>i});var o=JSON.parse('{"id":"language/basics/lang-errors","title":"Error handling","description":"Error handling is the process of anticipating and responding to errors that might occur in your application. Qodly provides a comprehensive support for catching and reporting errors at runtime, as well as for investigating their conditions.","source":"@site/versioned_docs/version-1.1.0/language/basics/lang-errors.md","sourceDirName":"language/basics","slug":"/language/basics/lang-errors","permalink":"/docs/language/basics/lang-errors","draft":false,"unlisted":false,"editUrl":"https://github.com/qodly/docs/issues/new?title=Comment%20on%20language%2Fbasics%2Flang-errors.md%20(1.1.0)&body=Share%20any%20feedback%20about%20this%20page%20%E2%80%94%20report%20issues%2C%20suggest%20improvements%2C%20or%20tell%20us%20what%E2%80%99s%20helpful.%0A%0AIf%20it%E2%80%99s%20an%20issue%3A%0A-%20What%E2%80%99s%20the%20issue%3F%20(e.g.%2C%20typo%2C%20incorrect%20information%2C%20unclear%20explanation)%0A-%20Where%20is%20it%3F%20(e.g.%2C%20section%20name%2C%20specific%20paragraph%2C%20or%20line)%0A%0AThank%20you%20for%20helping%20us%20improve!%20%F0%9F%9A%80%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20","tags":[],"version":"1.1.0","frontMatter":{"id":"lang-errors","title":"Error handling"},"sidebar":"Develop","previous":{"title":"Control flow","permalink":"/docs/language/basics/lang-control-flow"},"next":{"title":"Identifiers","permalink":"/docs/language/basics/lang-identifiers"}}'),t=r("85893"),s=r("50065");let i={id:"lang-errors",title:"Error handling"},a=void 0,l={},c=[{value:"Error or status",id:"error-or-status",level:2},{value:"Installing an error-handling method",id:"installing-an-error-handling-method",level:2},{value:"Scope and components",id:"scope-and-components",level:3},{value:"Handling errors within the method",id:"handling-errors-within-the-method",level:3},{value:"Example",id:"example",level:4},{value:"Using an empty error-handling method",id:"using-an-empty-error-handling-method",level:3},{value:"try(expression)",id:"tryexpression",level:2},{value:"Examples",id:"examples",level:3},{value:"try...catch...end",id:"trycatchend",level:2},{value:"Example",id:"example-1",level:3}];function d(e){let n={a:"a",admonition:"admonition",code:"code",em:"em",h2:"h2",h3:"h3",h4:"h4",li:"li",ol:"ol",p:"p",pre:"pre",strong:"strong",ul:"ul",...(0,s.a)(),...e.components};return(0,t.jsxs)(t.Fragment,{children:[(0,t.jsx)(n.p,{children:"Error handling is the process of anticipating and responding to errors that might occur in your application. Qodly provides a comprehensive support for catching and reporting errors at runtime, as well as for investigating their conditions."}),"\n",(0,t.jsx)(n.p,{children:"Error handling meets two main needs:"}),"\n",(0,t.jsxs)(n.ul,{children:["\n",(0,t.jsx)(n.li,{children:"finding out and fixing potential errors and bugs in your code during the development phase,"}),"\n",(0,t.jsx)(n.li,{children:"catching and recovering from unexpected errors in deployed applications; in particular, you can replace system error messages with you own interface."}),"\n"]}),"\n",(0,t.jsx)(n.p,{children:"Basically, there are two ways to handle errors in QodlyScript. You can:"}),"\n",(0,t.jsxs)(n.ul,{children:["\n",(0,t.jsxs)(n.li,{children:[(0,t.jsx)(n.a,{href:"#installing-an-error-handling-method",children:"install an error-handling method"}),", or"]}),"\n",(0,t.jsxs)(n.li,{children:["use a ",(0,t.jsxs)(n.a,{href:"#tryexpression",children:[(0,t.jsx)(n.code,{children:"try()"})," keyword"]})," or a ",(0,t.jsxs)(n.a,{href:"#trycatchend",children:[(0,t.jsx)(n.code,{children:"try/catch"})," structure"]})," before pieces of code that call a function, method, or expression that can throw an error."]}),"\n"]}),"\n",(0,t.jsx)(n.h2,{id:"error-or-status",children:"Error or status"}),"\n",(0,t.jsxs)(n.p,{children:["Many QuodlyScript class functions, such as ",(0,t.jsx)(n.code,{children:"entity.save()"})," or ",(0,t.jsx)(n.code,{children:"transporter.send()"}),", return a ",(0,t.jsx)(n.em,{children:"status"}),' object. This object is used to store "predictable" errors in the runtime context, e.g. invalid password, locked entity, etc., that do not stop program execution. This category of errors can be handled by regular code.']}),"\n",(0,t.jsxs)(n.p,{children:['Other "unpredictable" errors include write error, network failure, or in general any unexpected interruption. This category of errors generates exceptions and needs to be handled through an error-handling method or a ',(0,t.jsx)(n.code,{children:"try()"})," keyword."]}),"\n",(0,t.jsx)(n.h2,{id:"installing-an-error-handling-method",children:"Installing an error-handling method"}),"\n",(0,t.jsxs)(n.p,{children:["In Qodly, all errors can be caught and handled by specific methods, named ",(0,t.jsx)(n.strong,{children:"error-handling"})," (or ",(0,t.jsx)(n.strong,{children:"error-catching"}),") methods."]}),"\n",(0,t.jsx)(n.p,{children:"Once installed, error handlers are automatically called in case of error in the Qodly application. A different error handler can be called depending on the execution context (see below)."}),"\n",(0,t.jsxs)(n.p,{children:["To ",(0,t.jsx)(n.em,{children:"install"})," an error-handling method, you just need to call the ",(0,t.jsx)(n.a,{href:"/docs/language/commands/onErrCall",children:(0,t.jsx)(n.code,{children:"onErrCall"})})," command with the method name and (optionnally) scope as parameters. For example:"]}),"\n",(0,t.jsx)(n.pre,{children:(0,t.jsx)(n.code,{className:"language-qs",children:'onErrCall("IO_Errors",kLocal) //Installs a local error-handling method\n'})}),"\n",(0,t.jsxs)(n.p,{children:["To stop catching errors for an execution context and give back hand, call ",(0,t.jsx)(n.code,{children:"onErrCall"})," with an empty string:"]}),"\n",(0,t.jsx)(n.pre,{children:(0,t.jsx)(n.code,{className:"language-qs",children:'onErrCall("",kLocal) //gives back control for the local process\n'})}),"\n",(0,t.jsxs)(n.p,{children:["The  ",(0,t.jsx)(n.a,{href:"/docs/language/commands/methodCalledOnError",children:(0,t.jsx)(n.code,{children:"methodCalledOnError"})})," command allows you to know the name of the method installed by ",(0,t.jsx)(n.code,{children:"onErrCall"})," for the current process. It is particularly useful in the context of generic code because it enables you to temporarily change and then restore the error-catching method:"]}),"\n",(0,t.jsx)(n.pre,{children:(0,t.jsx)(n.code,{className:"language-qs",children:' var methCurrent : string\n methCurrent = methodCalledOnError(kLocal)\n onErrCall("NewMethod",kLocal)\n  ...//Processing with specific error handling\n  //Reinstallation of previous method\n onErrCall(methCurrent,kLocal)\n\n'})}),"\n",(0,t.jsx)(n.h3,{id:"scope-and-components",children:"Scope and components"}),"\n",(0,t.jsx)(n.p,{children:"An error-handling method can be set for different execution contexts:"}),"\n",(0,t.jsxs)(n.ul,{children:["\n",(0,t.jsxs)(n.li,{children:["for the ",(0,t.jsx)(n.strong,{children:"current process"}),"- a local error handler will be only called for errors that occurred in the current process of the current project,"]}),"\n",(0,t.jsxs)(n.li,{children:["for the ",(0,t.jsx)(n.strong,{children:"whole application"}),"- a global error handler will be called for all errors that occurred in the application execution context of the current project."]}),"\n"]}),"\n",(0,t.jsx)(n.p,{children:"Examples:"}),"\n",(0,t.jsx)(n.pre,{children:(0,t.jsx)(n.code,{className:"language-qs",children:'onErrCall("IO_Errors",kLocal) //Installs a local error-handling method\nonErrCall("globalHandler",kGlobal) //Installs a global error-handling method\n'})}),"\n",(0,t.jsx)(n.p,{children:'You can install a global error handler that will serve as "fallback" and specific local error handlers for certain processes.'}),"\n",(0,t.jsx)(n.p,{children:"You can define a single error-catching method for the whole application or different methods per application module. However, only one method can be installed per execution context and per project. When an error occurs, only one method is called."}),"\n",(0,t.jsx)(n.h3,{id:"handling-errors-within-the-method",children:"Handling errors within the method"}),"\n",(0,t.jsx)(n.p,{children:"Within a custom error method, you can use several commands that will help you identifying the error:"}),"\n",(0,t.jsxs)(n.ul,{children:["\n",(0,t.jsxs)(n.li,{children:["the ",(0,t.jsx)(n.a,{href:"/docs/language/commands/lastErrors",children:(0,t.jsx)(n.code,{children:"lastErrors"})})," command that returns a collection of the current stack of errors that occurred in the Qodly application."]}),"\n",(0,t.jsxs)(n.li,{children:["the ",(0,t.jsx)(n.a,{href:"/docs/language/commands/callChain",children:(0,t.jsx)(n.code,{children:"callChain"})})," command that returns a collection of objects describing each step of the method call chain within the current process."]}),"\n"]}),"\n",(0,t.jsx)(n.h4,{id:"example",children:"Example"}),"\n",(0,t.jsx)(n.p,{children:"Here is a simple error-handling system:"}),"\n",(0,t.jsx)(n.pre,{children:(0,t.jsx)(n.code,{className:"language-qs",children:'// installing the error handling method\n onErrCall("errorMethod")\n //... executing code\n onErrCall("") //giving control back to Qodly\n'})}),"\n",(0,t.jsx)(n.pre,{children:(0,t.jsx)(n.code,{className:"language-qs",children:'// errorMethod project method  \nvar errNum : integer\nvar message : string\nerrNum = lastErrors[0].errCode\nif(errNum  !=  1006) //this is not a user interruption\n   message = "Error "+string(errNum)+" occurred ("+lastErrors[0].message+").")\nend\n'})}),"\n",(0,t.jsx)(n.h3,{id:"using-an-empty-error-handling-method",children:"Using an empty error-handling method"}),"\n",(0,t.jsxs)(n.p,{children:["If you mainly want the standard error messages to be hidden, you can install an empty error-handling method. The ",(0,t.jsx)(n.a,{href:"/docs/language/commands/lastErrors",children:(0,t.jsx)(n.code,{children:"lastErrors"})})," command can be called in any method, i.e. outside of the error-handling method:"]}),"\n",(0,t.jsx)(n.pre,{children:(0,t.jsx)(n.code,{className:"language-qs",children:'onErrCall("emptyMethod") //emptyMethod exists but is empty\nvar errNum : integer\nvar errText : string\nif (errNum == -43)\n	errText = "File not found."\nend\nonErrCall("")\n'})}),"\n",(0,t.jsx)(n.h2,{id:"tryexpression",children:"try(expression)"}),"\n",(0,t.jsxs)(n.p,{children:["The ",(0,t.jsx)(n.code,{children:"try(expression)"})," statement allows you to test a single-line expression in its actual execution context (including, in particular, variable values) and to intercept errors it throws so that the Qodly error dialog box is not displayed. Using ",(0,t.jsx)(n.code,{children:"try(expression)"})," provides an easy way to handle simple error cases with a very low number of code lines, and without requiring an error-handling method."]}),"\n",(0,t.jsxs)(n.p,{children:["The formal syntax of the ",(0,t.jsx)(n.code,{children:"try(expression)"})," statement is:"]}),"\n",(0,t.jsx)(n.pre,{children:(0,t.jsx)(n.code,{className:"language-qs",children:"\ntry (expression) : any | undefined\n\n"})}),"\n",(0,t.jsxs)(n.p,{children:[(0,t.jsx)(n.em,{children:"expression"})," can be any valid expression."]}),"\n",(0,t.jsxs)(n.p,{children:["If an error occurred during its execution, it is intercepted and no error dialog is displayed, whether an ",(0,t.jsx)(n.a,{href:"#installing-an-error-handling-method",children:"error-handling method"})," was installed or not before the call to ",(0,t.jsx)(n.code,{children:"try()"}),". If ",(0,t.jsx)(n.em,{children:"expression"})," returns a value, ",(0,t.jsx)(n.code,{children:"try()"})," returns the last evaluated value, otherwise it returns ",(0,t.jsx)(n.code,{children:"undefined"}),"."]}),"\n",(0,t.jsxs)(n.p,{children:["You can handle the error(s) using the ",(0,t.jsx)(n.a,{href:"/docs/language/commands/lastErrors",children:(0,t.jsx)(n.code,{children:"lastErrors"})})," command. If ",(0,t.jsx)(n.em,{children:"expression"})," throws an error within a stack of ",(0,t.jsx)(n.code,{children:"try()"})," calls, the execution flow stops and returns to the latest executed ",(0,t.jsx)(n.code,{children:"try()"})," (the first found back in the call stack)."]}),"\n",(0,t.jsx)(n.admonition,{type:"note",children:(0,t.jsxs)(n.p,{children:["If an ",(0,t.jsx)(n.a,{href:"#installing-an-error-handling-method",children:"error-handling method"})," is installed by ",(0,t.jsx)(n.em,{children:"expression"}),", it is called in case of error."]})}),"\n",(0,t.jsx)(n.h3,{id:"examples",children:"Examples"}),"\n",(0,t.jsxs)(n.ol,{children:["\n",(0,t.jsx)(n.li,{children:"You want to display the contents of a file if the file can be open without error, and if its contents can be read. You can write:"}),"\n"]}),"\n",(0,t.jsx)(n.pre,{children:(0,t.jsx)(n.code,{className:"language-qs",children:'var text : string\nvar file : 4D.File = file("/SOURCES/Shared/myFile.txt")\nvar fileHandle : 4D.FileHandle = try(file.open())\nif (fileHandle != null)\n  text = try(fileHandle.readText()) || "Error reading the file"\nend\n'})}),"\n",(0,t.jsxs)(n.ol,{start:"2",children:["\n",(0,t.jsx)(n.li,{children:"You want to handle the divide by zero error. In this case, you want to return 0 and log an error:"}),"\n"]}),"\n",(0,t.jsx)(n.pre,{children:(0,t.jsx)(n.code,{className:"language-qs",children:'function divide( p1 : real , p2 : real) -> result : real\n  if (p2 == 0)\n     result = 0 //only for clarity (0 is the default for reals)\n     throw(-12345 , "Division by zero")\n  else\n    result = p1/p2\n  end\n\nfunction test() -> result : real\n  var info = string\n  result = try(divide(p1 , p2))\n  if (lastErrors != null)\n    info = "Error"\n  end\n\n'})}),"\n",(0,t.jsxs)(n.ol,{start:"3",children:["\n",(0,t.jsxs)(n.li,{children:["You want to handle both ",(0,t.jsx)(n.a,{href:"#error-or-status",children:"predictable and non-predictable"})," errors:"]}),"\n"]}),"\n",(0,t.jsx)(n.pre,{children:(0,t.jsx)(n.code,{className:"language-qs",children:'var e = ds.Employee.new()\nvar status = object\nvar info = string\ne.name = "Smith"\nstatus = try(e.save()) //catch predictable and non-predictable errors\nif (status.success)\n   info = "Success"\nelse\n   info = "Error: "+jsonStringify(status.errors)\nend\n\n'})}),"\n",(0,t.jsx)(n.h2,{id:"trycatchend",children:"try...catch...end"}),"\n",(0,t.jsxs)(n.p,{children:["The ",(0,t.jsx)(n.code,{children:"try...catch...end"})," structure allows you to test a block code in its actual execution context (including, in particular, variable values) and to intercept errors it throws so that the no Qodly error is displayed."]}),"\n",(0,t.jsxs)(n.p,{children:["Unlike the ",(0,t.jsx)(n.code,{children:"try(expression)"})," keyword that evaluates a single-line expression, the ",(0,t.jsx)(n.code,{children:"try...catch...end"})," structure allows you to evaluate any code block, from the most simple to the most complex, without requiring an error-handling method. In addition, the ",(0,t.jsx)(n.code,{children:"catch"})," block can be used to handle the error in any custom way."]}),"\n",(0,t.jsxs)(n.p,{children:["The formal syntax of the ",(0,t.jsx)(n.code,{children:"try...catch...end"})," structure is:"]}),"\n",(0,t.jsx)(n.pre,{children:(0,t.jsx)(n.code,{className:"language-qs",children:"\ntry \n	statement(s) // Code to evaluate\ncatch\n	statement(s) // Code to execute in case of error\nend\n\n"})}),"\n",(0,t.jsxs)(n.p,{children:["The code placed between the ",(0,t.jsx)(n.code,{children:"try"})," and the ",(0,t.jsx)(n.code,{children:"catch"})," keywords is first executed, then the flow depends on the error(s) encountered during this execution."]}),"\n",(0,t.jsxs)(n.ul,{children:["\n",(0,t.jsxs)(n.li,{children:["If no error is thrown, the code execution continues after the corresponding ",(0,t.jsx)(n.code,{children:"end"})," keyword. The code placed between the ",(0,t.jsx)(n.code,{children:"catch"})," and the ",(0,t.jsx)(n.code,{children:"end"})," keywords is not executed."]}),"\n",(0,t.jsxs)(n.li,{children:["If the code block execution throws a ",(0,t.jsx)(n.em,{children:"non-deferred error"}),", the execution flow stops and executes the corresponding ",(0,t.jsx)(n.code,{children:"catch"})," code block."]}),"\n",(0,t.jsxs)(n.li,{children:["If the code block execution throws a ",(0,t.jsx)(n.em,{children:"deferred error"}),", the execution flow continues until the end of the ",(0,t.jsx)(n.code,{children:"try"})," block and then executes the corresponding ",(0,t.jsx)(n.code,{children:"catch"})," code block."]}),"\n"]}),"\n",(0,t.jsx)(n.admonition,{type:"note",children:(0,t.jsxs)(n.p,{children:["If a ",(0,t.jsx)(n.em,{children:"deferred"})," error is thrown outside of the ",(0,t.jsx)(n.code,{children:"try"})," block, the code execution continues until the end of the method or function."]})}),"\n",(0,t.jsx)(n.admonition,{type:"info",children:(0,t.jsxs)(n.p,{children:["For more information on ",(0,t.jsx)(n.em,{children:"deferred"})," and ",(0,t.jsx)(n.em,{children:"non-deferred"})," errors, please refer to the ",(0,t.jsx)(n.a,{href:"/docs/language/commands/throw",children:(0,t.jsx)(n.code,{children:"throw"})})," command description."]})}),"\n",(0,t.jsxs)(n.p,{children:["In the ",(0,t.jsx)(n.code,{children:"catch"})," code block, you can handle the error(s) using standard error handling commands. The ",(0,t.jsx)(n.a,{href:"/docs/language/commands/lastErrors",children:(0,t.jsx)(n.code,{children:"lastErrors"})})," command contains the last errors collection. You can ",(0,t.jsx)(n.a,{href:"#installing-an-error-handling-method",children:"declare an error-handling method"})," in this code block, in which case it is called in case of error."]}),"\n",(0,t.jsx)(n.admonition,{type:"note",children:(0,t.jsxs)(n.p,{children:["If an ",(0,t.jsx)(n.a,{href:"#installing-an-error-handling-method",children:"error-handling method"})," is installed in the code placed between the ",(0,t.jsx)(n.code,{children:"try"})," and the ",(0,t.jsx)(n.code,{children:"catch"})," keywords, it is called in case of error."]})}),"\n",(0,t.jsx)(n.h3,{id:"example-1",children:"Example"}),"\n",(0,t.jsxs)(n.p,{children:["Combining transactions and ",(0,t.jsx)(n.code,{children:"try...catch...end"})," structures allows writing secured code for critical features."]}),"\n",(0,t.jsx)(n.pre,{children:(0,t.jsx)(n.code,{className:"language-qs",children:"function createInvoice(customer : cs.customerEntity, items : collection, invoiceRef : string) : cs.invoiceEntity\n	var newInvoice : cs.invoiceEntity\n	var newInvoiceLine : cs.invoiceLineEntity\n	var item : object\n	ds.startTransaction()\n	try\n		newInvoice=this.new()\n		newInvoice.customer=customer\n		newInvoice.invoiceRef=invoiceRef\n		forEach (item, items)\n			newInvoiceLine=ds.invoiceLine.new()\n			newInvoiceLine.item=item.item\n			newInvoiceLine.amountitem.amount\n			newInvoiceLine.invoice=newInvoice\n			//call other specific functions to validate invoiceline\n			newInvoiceLine.save()\n		end \n		newInvoice.save()\n		ds.validateTransaction()\n	catch\n		ds.cancelTransaction()\n		ds.logErrors(lastErrors)\n		newInvoice=null\n	end\n	return newInvoice\n\n"})})]})}function h(e={}){let{wrapper:n}={...(0,s.a)(),...e.components};return n?(0,t.jsx)(n,{...e,children:(0,t.jsx)(d,{...e})}):d(e)}},50065:function(e,n,r){r.d(n,{Z:function(){return a},a:function(){return i}});var o=r(67294);let t={},s=o.createContext(t);function i(e){let n=o.useContext(s);return o.useMemo(function(){return"function"==typeof e?e(n):{...n,...e}},[n,e])}function a(e){let n;return n=e.disableParentContext?"function"==typeof e.components?e.components(t):e.components||t:i(e.components),o.createElement(s.Provider,{value:n},e.children)}}}]);